### ISSUE TITLE
Wrong yaml-file name for Inventory/Item/Drive

### ISSUE THREAD

**Issue by Kitsok** [openbmc/phosphor-dbus-interfaces#11]
Hello!

xyz/openbmc_project/Inventory/Item/Drive.Interface.yaml file has wrong name (capital I in Interface) thus it's not processed.

**Comment by wltu** [comment]
Just ran into this issue and have the fix here: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-dbus-interfaces/+/43632

I don't think many people use the github issues... sorry about the delay.
