### ISSUE TITLE
mctpd integrate miss dependency

### ISSUE THREAD

**Issue by chenhongbo2022** [openbmc/phosphor-dbus-interfaces#16]
Compile mctpd miss dependency，this open source depends the third library phosphor-dbus-interfaces，such as：

#include <xyz/openbmc_project/MCTP/Base/server.hpp>
#include <xyz/openbmc_project/MCTP/SupportedMessageTypes/server.hpp>
But I did't find the corresponding file from phosphor-dbus-interfaces，Where can i get the dependent files？
Am i looking for the right one？Not uploaded to openbmc GitHub？

I want to integrate thie to BMC. How should i integrate mctpd to bmc?

**Comment by williamspatrick** [comment]
We don’t have any mctpd that I am aware of. Can you point me to this “open source”. If it is something in another organization, they have probably hijacked our project dbus interface names without contributing them back to us.

**Comment by rebeccasf** [comment]
Hi, I had the same issue when building https://github.com/Intel-BMC/mctpd, I think this repo was outdated? Or does the implementation moved to somewhere within openbmc?

**Comment by williamspatrick** [comment]
The recommendation is to use the in-kernel MCTP subsystem and the userspace daemon from CodeConstruct.  I don't know what the Intel mctpd was doing. The CodeConstruct one is for endpoint management only and not part of the protocol transport path.

**Comment by amboar** [comment]
Specifically, the userspace daemon @williamspatrick mentions is https://github.com/CodeConstruct/mctp. This is automatically installed in your image if you enable the `mctp` in `DISTRO_FEATURES` in OpenBMC. Enabling the `mctp` distro feature is best done by adding `require require conf/distro/include/mctp.inc` (https://github.com/openbmc/openbmc/blob/master/meta-phosphor/conf/distro/include/mctp.inc) to your platform config.
