### ISSUE TITLE
User/LDAP:- Remove the secureLDAP property from the D-Bus Interface

### ISSUE THREAD

**Issue by ratagupt** [openbmc/phosphor-dbus-interfaces#3]
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/User/Ldap/Config.interface.yaml

We can identify the secure-LDAP from the LDAPServerURI property.
URI for secure starts with ldaps://
URI for non secure LDAP starts with ldap://

**Comment by bradbishop** [comment]
There doesn't seem to be any interest in this issue.  Closing.
