### ISSUE TITLE
Error in ./configure for phosphor-dbus-interfaces

### ISSUE THREAD

**Issue by gchik** [openbmc/phosphor-dbus-interfaces#7]
I'm newbie in OpenBMC. I started from the begining: https://github.com/openbmc/docs/tree/master/development and successfully made first step - Development Environment Setup. Now I'm trying to build Hello World in SDK (https://github.com/openbmc/docs/blob/master/development/sdk-hello-world.md).
When I use command:

./configure ${CONFIGURE_FLAGS}

I get ERROR

...
checking for PHOSPHOR_DBUS_INTERFACES... no
configure: error: Package requirements (phosphor-dbus-interfaces) were not met:

No package 'phosphor-dbus-interfaces' found

What is this error means? What I need to do to fix it?

Next, I'm trying to build PHOSPHOR_DBUS_INTERFACES repo.
I start ./bootstrap.sh script. It pass OK.
I start ./configure ${CONFIGURE_FLAGS} and get error

...
./configure: line 9073: syntax error near unexpected token `noext'
./configure: line 9073: `    AX_CXX_COMPILE_STDCXX_17(noext)'

How to fix this ERROR?

**Comment by bradbishop** [comment]
@gchik apologies - I don't monitor this issue queue.  Did you ever figure this out?

**Comment by gchik** [comment]
@bradbishop, thanks for reply. I did not figure out this issue. I was switched for another task. May be I not full install some components for OpenBMC development

**Comment by matthewfischer** [comment]
Can we close this issue now?
